#网关服务同样需要连接eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka/

#hystrix properties
#hystrix:
#  threadpool:
#    default:
#      coreSize: 3
server:
  port: 5555
management:
  endpoints:
    web:
      exposure:
        include: "*"
#config routes by manual
zuul:
  routes:
    organizationservice: /organization/**
    licensingservice: /licensing/**
    configserver: configserver/**
    #静态路由配置 该service不注册到eureka服务发现中#
    licensestatic:
      path: /licensestatic/**
      url: http://localhost:9090/
   # exclude auto routes by zuul #
  #ignored-services: "*"
  ignored-services: ["organizationservice","licensingservice"]
#  prefix: /api

#note 可以将该文件的路由配置中心数据转移到spring-confsvr中以实现动态重新加载路由配置#