server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///E:/workspace/springboot-demo/spring-confsvr/src/main/resources/config/licensingservice
