#消费者同样需要连接eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalut: http://localhost:8761/eureka/

signing:
  key: 345345fsdgsf5345

redis:
  server: 118.31.122.126
  port: 6379


#hystrix properties
#hystrix:
#  threadpool:
#    default:
#      coreSize: 3



security:
  oauth2:
    client:
      grant-type: client_credentials
    resource:
      user-info-uri: http://localhost:8901/auth/user
#配置log 日志级别#
logging:
  level:
    root: info
