tracer.property: "I AM THE  ZUULSERVICE SERVICE DEFAULT"
zuul.prefix: /api
zuul.ignored-services: "*"
zuul.routes.organizationservice: /organization/**
zuul.routes.licensingservice: /licensing/**
zuul.routes.configserver: configserver/**
zuul.routes.licensestatic.path: /licensestatic/**
zuul.routes.licensestatic.url: http://localhost:9090/
#设置敏感的HTTP头部以阻止传播到下游  默认敏感头部为Cookie, Set-Cookie,Authorization
#设置为 Cookie, Set-Cookie则其他的头部可以传播到下游 比如Authorization

zuul.sensitive-headers: Cookie,setCookie

spring.jpa.database: "mysql"
spring.jpa.show-sql: "true"
spring.datasource.driver-class-name: "com.mysql.cj.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://118.31.122.126:3306/spring_cloud_default?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT%2B8"
spring.datasource.username: "Jesse"
spring.datasource.password: "Jesse@123456"
