eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalut: http://localhost:8761/eureka/
server:
  port: 8082

#    user:
#      name: admin
#      password: 123456
#security:

signing:
  key: 345345fsdgsf5345


security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8901/auth/user
