server:
  servlet:
    context-path: /spring_data
  port: 8081
spring:
  datasource:
    db1:  #数据源1
      jdbc-url: jdbc:mysql://118.31.122.126:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: Jesse
      password: Jesse@123456
      driver-class-name: com.mysql.cj.jdbc.Driver

    db2:  #数据源1
      jdbc-url: jdbc:mysql://118.31.122.126:3306/test2?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: Jesse
      password: Jesse@123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    elasticsearch:
      cluster-nodes: localhost:9200
config:
  path: E:\workspace\application.properties